### ISSUE TITLE
Lista general de tareas - SPRINT 0

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#1]
Esta issue se cierra una vez que las siguientes tareas estén finalizadas: 
- Conformación de grupo
- Envío de formulario con datos de integrantes
- Estructuración de proyecto en github (Issues, milestones, tablero Kanban, creación de ramas)
- Creación de la Wiki para documentar la información de las ceremonias Scrum
- Conformación del documento IEEE-830
- Creación de la documentación correspondiente a las historias de usuarios

**Comment by DenisseSabeff** [comment]
Estoy terminando de actualizar el documento con formato ieee-830. Como mencioné en la ultima daily, estoy actualizando el documeto del año 2023 a este año.

**Comment by MariaVictoria** [comment]
Perfecto chicos, termino de actualizar bitácora en cuanto al stakeholder. Actualizo documento historias de usuario y edito la wiki

**Comment by Js-Alvarez** [comment]
Estructure la base para realizar la planning poker

**Comment by DenisseSabeff** [comment]
El documento de requerimientos de software con formato IEEE-830 está listo y estaré pendiente de cualquier actualización que surja. Dejé el enlace correspondiente al DocDrive en la Wiki. 
También corregí la bitácora de registro de nuestro trabajo hasta el momento y estaré atenta para cualquier actualización que sea necesaria.

**Comment by bit-rec98** [comment]
Tareas de las que soy responsable en este sprint finalizadas:
- La conformación del grupo de desarrollo está lista
- El envío del formulario con los datos de los integrantes está realizado
- La estructuración del proyecto en GitHub (creación de Issues. milestones, la creación del tablero Kanban y la ramificación del proyecto para que cada integrante tenga su rama lista junto con la rama main y development) está lista.
