### ISSUE TITLE
#US09 #TK01 Creación del componente Panel de Control

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#10]
Está issue se ha creado para documentar el proceso de desarrollo del componente PANEL DE CONTROL junto con sus componentes particulares en el proyecto.

**Comment by bit-rec98** [comment]
Desarrollo del panel de control (dashboard) para clientes en desarrollo.

**Comment by DenisseSabeff** [comment]
#53

**Comment by DenisseSabeff** [comment]
#53
