### ISSUE TITLE
#Us09#Tk02 Crear métodos para renderizar en las tablas de pedidos 

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#102]
#53  Crear métodos para renderizar en las tablas de pedidos (Resumen de pedidos, historial de pedidos y estado de pedidos)

**Comment by LautaroPena02** [comment]
Métodos creados, aun realizando pruebas para verificar que todo funcione correctamente.
