### ISSUE TITLE
#Us02#Tk02 Desarrollo de formulario reactivo para registro.

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#106]
#45

**Comment by DenisseSabeff** [comment]
Esta subido el codigo para el form de Registro! Coordinamos con Victoria y ella completó el codigo para verificar que la confirmación de contraseña sea correcta. Hasta el momento estamos utilizando una api de prueba para corroborar las peticiones.

**Comment by MariaVictoria** [comment]
Denisse, subo un pequeño ajuste en una ruta.

**Comment by DenisseSabeff** [comment]
Esta lista la funcionalidad, pero estoy una api de prueba. Queda que cuando se suba el backend, pueda corregir los campos en base a la conexión.
