### ISSUE TITLE
#US03#TK03 - Crear métodos para deshabilitar botones "Ir al carro" y "Agregar al carro"

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#113]
Estos botones se van a deshabilitar cuando el usuario no haya iniciado sesión con su cuenta.

**Comment by bit-rec98** [comment]
#9

**Comment by junegrete** [comment]
se crearon los botones y debido a unos inconvenientes el botón de Ir al carro fue sacado.
