### ISSUE TITLE
#US03 #TK01 Integramos funcionalidad de carga de productos al carrito de compras.

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#12]
#9 Esta issue se ha creado con el objetivo de documentar el desarrollo de la funcionalidad de carga de productos al carro de compras.

**Comment by bit-rec98** [comment]
Desarrollo de la base de datos ficticia "db.json" en progreso.

**Comment by LautaroPena02** [comment]
Funcionalidad en progreso.

**Comment by bit-rec98** [comment]
Desarrollo de la interfaz para la carga de productos al carrito de compras en progreso, desarrollo estático concluido.

**Comment by DenisseSabeff** [comment]
Implementamos funcionalidad para el carrito en el sprint 2.
