### ISSUE TITLE
#US08 #TK01 Implementar funcionalidad de seguimiento externo del pedido.

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#13]
#52 Esta issue se ha creado para documentar el proceso de desarrollo de la creación de la funcionalidad para darle seguimiento externo a un pedido creado.

**Comment by bit-rec98** [comment]
Desarrollo de los servicios en progreso.

**Comment by MariaVictoria** [comment]
Perfecto Cristian. quedo atenta a cualquier notificación

**Comment by MariaVictoria** [comment]
Se implementa botón de enlace a la página de la entidad de entregas de pedido para hacer seguimiento externo
