### ISSUE TITLE
#Admin01 #TK04 Revisión de la base de datos 

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#21]
#43 En esa issue se comentan las conclusiones de la revisión de la base de datos para la característica indicada en el título.

**Comment by toskamon** [comment]
se realizaron cambios en la base de datos, agregándose atributos como password en la tabla de usuarios. Se comprobó la conexión y se hizo un test para verificar que los datos estén relacionados correctamente
