### ISSUE TITLE
#Admin01 #TK02 Creación y desarrollo de los modelos de datos

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#22]
#43 En esta issue se comentan detalles acerca del proceso de desarrollo de los modelos de datos creados con los lenguajes Python y Django.

**Comment by toskamon** [comment]
Se desarrollaron los modelos de datos en función al avance del proyecto en el pasado semestre.Se registraron dichos modelos en la administración de la app (web) teniendo en cuenta las modificaciones de algunas tablas, y se agregaron métodos str en cada modelo para una representación futura.

**Comment by clau-yon** [comment]
Se realizaron el Diagrama de Casos de Uso y se modifico el Diagrama de Clases:
1.  En la clase Usuario fue cambiado el atributo DNI por Password.
2.  En la clase Producto se elimino el atributo Descripcion.
