### ISSUE TITLE
#Admin01 #TK01 Vinculación de los modelos de datos al administrador de Django 

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#23]
#43 En esta issue se documenta el proceso de desarrollo de la vinculación de los modelos de datos al usuario Administrador de Django con el objetivo de realizar un gestor de datos que utilice la metodología CRUD.

**Comment by toskamon** [comment]
La vinculación del modelo de datos en el administrador se desarrollo de manera correcta y se pudo ejecutar una prueba completa del sistema
