### ISSUE TITLE
#Admin01 #TK05 Crear un superusuario para poder acceder al Admin.

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#24]
#43 En esta issue se documenta el proceso de creación del "superusuario" que tendrá acceso como administrador al sitio Admin de django para poder gestionar la metodología CRUD creada.

**Comment by bit-rec98** [comment]
En esa issue también se informan las credenciales de acceso del superusuario para poder tener acceso al sitio de administración.

**Comment by toskamon** [comment]
Se creo un súper usuario con las siguientes credenciales:
Usuario : gustavo
password:1234
Se comprobó que dicho usuario tiene acceso al sistema de manera correcta y permite la realización del crud
