### ISSUE TITLE
#Admin01 #TK03 Desarrollo de la conexión al motor de datos

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#25]
#43 En esta issue se documenta el proceso de desarrollo de la configuración de la conexión al motor de la base de datos que se implementa en el proyecto para almacenar su información y gestionar consultas.

**Comment by toskamon** [comment]
Se configuro la conexión a la base de datos de manera satisfactoria
