### ISSUE TITLE
#US01 Tareas a desarrollar para la navegación del sitio.

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#3]
En esta lista se detallan las tareas a realizar en el desarrollo frontend del proyecto, las cuales van a tener su respectiva issue con detalles y encargados de realizarla.  Está issue va a estar destinada a resumir brevemente qué tareas son. Las tareas a realizar son: 
- Creación, desarrollo e interconexión de los siguientes componentes generales con sus respectivos componentes particulares: 
 
- [ ] #TK01 Crear un menú de navegación
- [ ] #TK02 Crear una página de inicio intuitiva con la vista rápida de productos destacados
- [ ] #TK03 Crear categorías de Productos por país
- [ ] #TK05 Navegación limitada a rutas declaradas

**Comment by DenisseSabeff** [comment]
Las siguientes issues corresponden a otras historias de usuario, por error de tipeo (de referencia) quedaron mal asignadas: 
#US08 #TK01 Creación de componentes Footer #5
#US09 #TK04 Creación del componente Panel de Control #10
#US06 #TK05 Creación del componente Acerca de Nosotros. #8

**Comment by MariaVictoria** [comment]
Perfecto Cristian, reviso tareas, y notifico.

**Comment by Js-Alvarez** [comment]
Desarrollado  la navegación del sitio.
