### ISSUE TITLE
#US02 Formularios de acceso

### ISSUE THREAD

**Issue by junegrete** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#45]
Implementamos formularios de registro e inicio de sesión.

- [x] #46
- [x] #47

**Comment by junegrete** [comment]
Se agregaron los respectivos formulario. Queda abierta para posibles mejoras.

**Comment by bit-rec98** [comment]
Desarrollo de la interfaz para los formularios de acceso de usuarios en progreso, desarrollo estático en progreso.
