### ISSUE TITLE
#US06 Seccion de contacto

### ISSUE THREAD

**Issue by junegrete** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#50]
Crearemos una sección que nos permita contactar con la empresa.

- [x] #TK01  Desarrollar interfaz "Sobre nosotros" y envío de formulario de contacto con todos los campos completos y un correo electrónico válido.

**Comment by DenisseSabeff** [comment]
Tal como comenté en la issue anterior, ya esta terminada esta sección. El form ya tiene sus validaciones.
