### ISSUE TITLE
#US08 Seguimiento externo de pedido

### ISSUE THREAD

**Issue by junegrete** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#52]
Implementar funcionalidad de seguimiento externo del pedido.

- [x] #TK01 Implementar funcionalidad de seguimiento externo del pedido.
- [x] #82

**Comment by MariaVictoria** [comment]
confirmo funcionalidad del boton de seguimiento de pedido a través de redireccionamiento a Andreani
