### ISSUE TITLE
#US09 Gestión de órdenes/pedidos

### ISSUE THREAD

**Issue by junegrete** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#53]
Creamos una sección que permitirá verificar los pedidos que he realizado a través de un panel intuitivo. 

- [x] #72
- [x] #73
- [x] #74

**Comment by bit-rec98** [comment]
Desarrollo de la interfaz para la gestión de órdenes/pedidos a nivel de usuario en progreso, desarrollo estático en progreso.
