### ISSUE TITLE
#US10 Sugerencias de alternativas de productos

### ISSUE THREAD

**Issue by junegrete** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#54]
Integraremos una sección que le permitirá al usuario poder visualizar rápidas sugerencias de productos nuevos o en promoción ofertas .

- [x] #71

**Comment by bit-rec98** [comment]
Desarrollo de la interfaz para el renderizado de sugerencias de productos en progreso, desarrollo estático en progreso.

**Comment by LautaroPena02** [comment]
Se lograron mejoras en los estilos para la tarjeta de sugerencias de productos del dashboard cliente.
