### ISSUE TITLE
#US01 #TK02 Creación del componente Landing Page

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#6]
#3 Esta issue se ha creado para documentar el proceso de desarrollo del componente LANDING PAGE junto con sus componentes particulares en el proyecto.

**Comment by MariaVictoria** [comment]
Gracias !

**Comment by MariaVictoria** [comment]
He subido una primera prueba para confirmar desarrollo.-

**Comment by MariaVictoria** [comment]
Termine de vincular las rutas de la landing !
