### ISSUE TITLE
#US04 #TK01 Implementar funcionalidad para eliminar productos del carrito de compras.

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#67]

**Comment by LautaroPena02** [comment]
Aun realizando las pruebas en la funcionalidad.

**Comment by bit-rec98** [comment]
Desarrollo de la interfaz para la la funcionalidad para eliminar productos del carro de compras en progreso, desarrollo estático en progreso.

**Comment by DenisseSabeff** [comment]
Implementamos funcionalidad en el sprint 2.
