### ISSUE TITLE
#US01 #TK03 Creación del componente Seccion Productos

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#7]
#3  Está issue se ha creado para documentar el proceso de desarrollo del componente SECCIÓN PRODUCTOS junto con sus componentes particulares en el proyecto.

**Comment by Js-Alvarez** [comment]
Terminado

**Comment by MariaVictoria** [comment]
Se terminaron de agregar imagenes que faltan vincular.
