### ISSUE TITLE
#Admin01 #TK06 Desarrollar característica para que los administradores puedan cargar nuevos productos.

### ISSUE THREAD

**Issue by DenisseSabeff** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#78]

**Comment by DenisseSabeff** [comment]
#43

**Comment by bit-rec98** [comment]
Desarrollo de la interfaz para la funcionalidad de agregar nuevos productos en el panel de control en progreso, desarrollo estático en progreso.

**Comment by toskamon** [comment]
ingreso al super usuario desde django
user= gustavo
pass= 1234
