### ISSUE TITLE
#US06 #TK05 Creación del componente Acerca de Nosotros.

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#8]
#50 Esta issue se ha creado para documentar el proceso de desarrollo del componente "ACERCA DE NOSOTROS" junto con sus componentes particulares en el proyecto.

**Comment by DenisseSabeff** [comment]
Chicos, la sección ya esta en proceso. Tal como hablamos hice un componente about con una breve descripción y otro componente para el formulario de contacto. Voy a ir enlazando la ruta para poder renderizar y probar los cambios. Pronto les comparto cuando finalice. Todavia estoy probando validaciones de los campos del form y los mensajes para el usuario en caso de error.

**Comment by DenisseSabeff** [comment]
Ya está subida la sección. El formulario está completo y con sus respectivas validaciones para que el usuario pueda mandar una consulta.

**Comment by DenisseSabeff** [comment]
#50
