### ISSUE TITLE
#US03 Sección Productos

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-integrador-ISPC-2024/proyecto-integrador-2024#9]
Está issue se ha creado para documentar el proceso de desarrollo del componente SECCIÓN CARRITO junto con sus componentes particulares en el proyecto.

- [x] #12
- [x] #65
- [x] #66

**Comment by bit-rec98** [comment]
Desarrollo de la sección carrito en desarrollo.

**Comment by LautaroPena02** [comment]
Se realizaron estilos en el carro y se agrearon los iconos en los botones.

**Comment by Js-Alvarez** [comment]
Sección Productos : Realizado

**Comment by Js-Alvarez** [comment]
Se genero la lógica para las peticiones y la implementación de la herramienta Claudinari para las imágenes

**Comment by toskamon** [comment]
se completo el desarrollo de productos desde backend

**Comment by Js-Alvarez** [comment]
Tarea terminada
